language: python
python:
  - "3.6.0"
install:
    - pip install -r requirements.txt
    - pip install braintree coveralls mock mysqlclient
env:
  - DB=postgres
addons:
  postgresql: "9.6.2"
script:
  - coverage run --omit=*/tests/* --source=hc manage.py test
after_success: coveralls
cache: pip
notifications:
  slack: andela:iGsVpql3P2556Vp8udoIW0k5
